### ISSUE TITLE
Add support of external solvers

### ISSUE THREAD

**Issue by nuft** [LA-EPFL/polympc#10]
Wrappers for external solvers should be added for validation and comparison purposes.

Suggested QP solvers for the SQP strategy:
- [HPIPM](https://github.com/giaf/hpipm)
- [qpOASES](https://projects.coin-or.org/qpOASES)
- [OSQP](https://github.com/oxfordcontrol/osqp)

**Comment by petlist** [comment]
Implemented interfaces to OSQP and QPMAD.
Implemented an interface to IPOPT.
