### ISSUE TITLE
Hessian from damped BFGS not always positive definite.

### ISSUE THREAD

**Issue by nuft** [LA-EPFL/polympc#13]
I noticed that the resulting hessian estimation form the damped BFGS implementation is in some rare cases indefinite.

There is a test reproducing this issue in [bfgs_test.cpp](https://github.com/LA-EPFL/polympc/blob/f9232ecb60316741d7357ab23abe5c5a5c0a9fa6/src/solvers/bfgs_test.cpp#L69-L85)

I will suspend this test for now, as I have no clue how to fix this issue.

**Comment by petlist** [comment]
Fixed.
