### ISSUE TITLE
Examples fail due to missing HSL dynamic library

### ISSUE THREAD

**Issue by nuft** [LA-EPFL/polympc#3]
The examples `kite_control_test`, `kite_model_test`, `kite_sode_test`, `legendre_test` run into an error because IPOPT doesn't find the HSL dynamic library libhsl.dylib.

We need to document how to install those dependencies.

**Comment by petlist** [comment]
1. HSL linear algebra libraries can be obtained here: http://www.hsl.rl.ac.uk/. Follow README there for installation instructions.

2. In the case when the licence is impossible to obtain, options can be set now to PSODESolver: 

`casadi::Dict solver_options;
solver_options["ipopt.linear_solver"] = "mumps";
PSODESolver<10,10,3,1>ps_solver(ode, tf, props, solver_options);`
