### ISSUE TITLE
Support the CG-based linear solver in QPs 

### ISSUE THREAD

**Issue by petlist** [LA-EPFL/polympc#5]
Implement a CG-based linear solver in the QP solver.

**Comment by nuft** [comment]
Addressed in d083c6416d57be380fc8c7511a35b182b4b53d0c.
Also works with `Eigen::ConjugateGradient`.

**Comment by nuft** [comment]
Compilation fails with ConjugateGradient.
How can we do template of template with variable number of arguments?

**Comment by nuft** [comment]
fixed in cf0704e44464016ef711d9faa1a45a2951614b87.
This works thanks to Eigen's consistent API, yay 🦉
