### ISSUE TITLE
CMakeLists: Redundant compiler options

### ISSUE THREAD

**Issue by nuft** [LA-EPFL/polympc#6]
In the CMakeLists some options are redundant.
For example the optimization `-O3` on this [line](https://github.com/LA-EPFL/polympc/blob/experimental/CMakeLists.txt#L12) which is overridden by the flags from `CMAKE_BUILD_TYPE`.

I propose to try to stick to [Modern CMake](https://cliutils.gitlab.io/modern-cmake/) practises.

**Comment by petlist** [comment]
Done.
