### ISSUE TITLE
Eigen assert fails in ConjugateGradient

### ISSUE THREAD

**Issue by nuft** [LA-EPFL/polympc#7]
When instantiating an `Eigen::ConjugateGradient` object with fixed-size matrices, an eigen_assert fails [here](https://github.com/eigenteam/eigen-git-mirror/blob/branches/3.3/Eigen/src/Core/PlainObjectBase.h#L281) at construction.

One can easily reproduce the problem when building with assertions enabled ("Debug" mode, NDEBUG not defined):

```
#include <Eigen/Dense>
#include <Eigen/IterativeLinearSolvers>

int main()
{
    Eigen::ConjugateGradient<Eigen::MatrixXd> cg2; // works fine
    Eigen::ConjugateGradient<Eigen::Matrix3d> cg1; // fails
}
```

**Comment by petlist** [comment]
Issue here: https://gitlab.com/libeigen/eigen/-/issues/1704
